name: Build & Release Arch OS ISO

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Set Environment
        run: echo "SNAPSHOT_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: Install Dependencies
        run: pacman -Syu --noconfirm archiso sudo

      - name: Build Arch OS ISO
        run: |
          cd ./iso
          SNAPSHOT_VERSION=${{ env.SNAPSHOT_VERSION }} bash build.sh

      - name: Upload Release dir to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./iso/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
